
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author sebu
 */
public class GameView extends javax.swing.JPanel implements ActionListener{
    private GameBoard gameBoard;
    private TreeMap<Integer, Integer> scores;
     DefaultListModel<String> listModel;
    final Timer timer = new Timer(150, this);
    
    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
        gameBoard = new GameBoard();
        jPanel1.add(gameBoard);
        listModel = new DefaultListModel<>();
        listModel.addElement(null);
        jList1.setModel(listModel);
    }
    
    public void addInput(int key){
        gameBoard.addInput(key);
    }
    
    public void initialize(){
        gameBoard.initiateGame();
        timer.stop();
    }
    
    public void initialize(int snakes,int food,int froogs){
        gameBoard.initiateGame(snakes, food, froogs);
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jList1 = new javax.swing.JList<>();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 5;
        add(jPanel1, gridBagConstraints);

        jPanel2.setMinimumSize(new java.awt.Dimension(150, 500));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 500));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("return to menu");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.SOUTH);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jPanel2.add(jList1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 5;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SnakeGame topFrame = (SnakeGame) SwingUtilities.getWindowAncestor(this);
//        System.out.print("ijgiugigv");
        topFrame.returnToMenu();
    }//GEN-LAST:event_jButton1ActionPerformed
    @Override
    public void actionPerformed(ActionEvent e) {
        gameBoard.actionPerformed(e);
        scores = gameBoard.getScores();
        List<Map.Entry<Integer, Integer>> sortedEntries = new ArrayList<>(scores.entrySet());
        Collections.sort(sortedEntries, Collections.reverseOrder(Map.Entry.comparingByValue()));
        String[] entryArray = sortedEntries.stream()
                .map(entry -> entry.getKey() + " snake: " + entry.getValue())
                .toArray(String[]::new);
  
        listModel.clear();
        for (String item : entryArray) {
            listModel.addElement(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
